@isTest
private class ProductControllerTest {

    @isTest
    static void testGetProducts() {
        // Test the controller method
        Test.startTest();
        
        Test.stopTest();
        // Assert the results
        System.assertEquals(10, 10);
    }

    @isTest
    static void testgetSimilarProducts() {
        // Test the controller method
        Test.startTest();
        
        Test.stopTest();
        // Assert the results
        System.assertEquals(10, 10);
    }
}
