name: ARM Trigger Test

on:
  workflow_dispatch:
    inputs:
      armRunId:
        required: false
        type: string

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print success message
        run: echo "GitHub Actions workflow triggered successfully. ARM Run ID: ${{ github.event.inputs.armRunId }}"
