name: ARM Trigger Test

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: "ARM project name"
        required: false
        type: string
      buildNumber:
        description: "ARM build number"
        required: false
        type: string
      sforgName:
        description: "Salesforce org name"
        required: false
        type: string

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print success message
        run: |
          echo "GitHub Actions workflow triggered successfully."
          echo "Project Name: ${{ github.event.inputs.projectName }}"
          echo "Build Number: ${{ github.event.inputs.buildNumber }}"
          echo "Salesforce Org: ${{ github.event.inputs.sforgName }}"
