name: Workflow B

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Convert Salesforce Metadata in force-app to JSON"]
    types: [completed]

jobs:
  run-opa:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_run'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JSON artifact
        uses: actions/download-artifact@v4
        with:
          name: salesforce-json
          path: json

      - name: Ensure JSON exists
        run: |
          if [ ! -d "json" ]; then
            echo "No JSON artifact found. Run WA first."
            exit 1
          fi

      - name: Evaluate OPA Policies
        run: |
          echo "Running OPA..."
          for file in $(find json -name "*.json"); do
            echo "Evaluating $file"
            opa eval --format pretty \
              --input "$file" \
              --data policies \
              "data"
          done
